# Generated by Django 5.1.6 on 2026-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsmeeting",
            name="chat_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
